### ISSUE TITLE
1.1.4 released without source in repository

### ISSUE THREAD

**Issue by llasram** [seiflotfy/rust-farmhash#11]
It looks like the only change from the repository is the version-bump, but it had me worried for a minute.

**Comment by seiflotfy** [comment]
with your stuff now in I will push it up to 1.1.5
ok?

**Comment by llasram** [comment]
Sound good to me.  Thank you!

**Comment by llasram** [comment]
Do you have an ETA on making a new release?

**Comment by seiflotfy** [comment]
This weekend I guess

**Comment by llasram** [comment]
Awesome, and no rush meant to be implied -- I'm just deciding if I need to pull this internally to avoid having my build depend on Github.  Thank you for creating and maintaining this library!
